import "./globals.css";
import Head from 'next/head';
import { Roboto } from '@next/font/google';

export const metadata = {
  title: "Google Legal Investigations",
  description: "Generated by Google Legal Investigations",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto', // Optional: CSS variable for Tailwind
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <head>
        <link rel="icon" href="/googleLogo.png" />
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
