import "./globals.css";
import Head from 'next/head';

export const metadata = {
  title: "Google Legal Investigations",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/googleLogo.png" />
      </head>
      <body className="antialiased" style={{ fontFamily: 'Roboto, Arial, sans-serif' }}>
        {children}
      </body>
    </html>
  );
}
